import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "@/redux/store/StoreProvider";
import { MainContextProvider } from "@/contexts/MainContext";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/assets/scss/style.scss";
import MainLayout from "@/components/Layout/MainLayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Booking Care",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContextProvider>
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>
            <MainLayout>
              <div id="main" className="container-fluid">
                {children}
              </div>
            </MainLayout>
          </body>
        </html>
      </StoreProvider>
    </MainContextProvider>
  );
}
