import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "@/redux/store/StoreProvider";
import { MainContextProvider } from "@/contexts/MainContext";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/style.scss";
import MainLayout from "@/components/Layout/MainLayout";
import "nprogress/nprogress.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Booking Care",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContextProvider>
      <StoreProvider>
        <html lang="en">
          <script
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDofN0TQ25L-6NhzMJGnT430QzuO_seZhg&libraries=places"
            async></script>

          <body className={inter.className}>
            <MainLayout>{children}</MainLayout>
          </body>
        </html>
      </StoreProvider>
    </MainContextProvider>
  );
}
