import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "@/redux/store/StoreProvider";
import { MainContextProvider } from "@/contexts/MainContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Booking Care",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainContextProvider>
      <StoreProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </StoreProvider>
    </MainContextProvider>
  );
}
